-- Job boards for the allowlisted companies that had none.
--
-- Generated by `node scripts/discover-job-boards.mjs --gaps`, which fingerprints
-- each company's careers site, derives the board config, and VERIFIES the board
-- returns real in-market jobs before offering it. Every row below was probed
-- live. Re-run that script to regenerate this file after adding companies.
--
-- Workday location facet ids are per-TENANT GUIDs read out of that tenant's own
-- `facets` response — they cannot be hardcoded, guessed, or shared between
-- boards. They are also the difference between a cheap run and an expensive
-- one: Roche's board is 1,191 requisitions worldwide and 9 in the UK.
--
-- Apply AFTER add_job_board_multi_ats.sql (which adds params/max_pages/
-- company_norm) and seed_job_board_multi_ats.sql (which adds the source rows).
-- The sources ship DISABLED, so nothing here runs until you enable them:
--
--   node scripts/run-job-ingest.mjs --dry-run --sources workday,oracle_orc,eightfold,jsonld
--   -- then flip `enabled` in the admin Sources tab
--
-- Safe to re-run.

INSERT INTO public.job_source_accounts
  (source, account, company, company_norm, markets, enabled, max_pages, domain, params)
VALUES
  -- locationCountry: United Kingdom (176)
  ('workday', 'lseg', 'London Stock Exchange', 'london stock exchange', ARRAY['gb'], true, 9, 'lseg.com', '{"tenant":"lseg","wd":3,"site":"Careers","facets":{"gb":{"locationCountry":["29247e57dbaf46fb855b224e03170bc7"]}}}'::jsonb),
  -- 716 jobs, 656 of them posted within the board's 21-day window, 25/page
  ('oracle_orc', 'marks-spencer', 'Marks & Spencer', 'marks and spencer', ARRAY['gb'], true, 27, 'marksandspencer.com', '{"host":"fa-eqid-saasfaprod1.fa.ocs.oraclecloud.com","siteNumber":"CX_1"}'::jsonb),
  ('eightfold', 'netflix', 'Netflix', 'netflix', ARRAY['gb'], true, 1, 'netflix.com', '{"host":"explore.jobs.netflix.net","domain":"netflix.com","location":"United Kingdom"}'::jsonb),
  -- locations: GBR-London-London (4), GBR-Scotland-Edinburgh (1), GBR-Scotland-Glasgow (1), GBR-South Yorkshire-Sheffield (1), GBR-Tyne and Wear-Newcastle (1)
  ('workday', 'mars', 'Mars', 'mars', ARRAY['gb'], true, 1, 'mars.com', '{"tenant":"mars","wd":3,"site":"External","facets":{"gb":{"locations":["f7694590cd5001d7d5375e48b00d8d9a","5f938dbcd9691000b0238b882fd40000","015abb4020e91000fc92f1611dc50000","1b66998de2de1000abd9039671ce0000","efa70fd7b4951001d03f5f829a6c0000"]}}}'::jsonb),
  -- locations: Antrim, United Kingdom (2), Ashford, United Kingdom (1), Banbridge, The Boulevard Retail Park, United Kingdom (3), Bicester, United Kingdom (1), Cheshire Oaks, Ellesmere Port, United Kingdom (1), Greenwich, United Kingdom (1) +12 more
  ('workday', 'nike', 'Nike', 'nike', ARRAY['gb'], true, 2, 'nike.com', '{"tenant":"nike","wd":1,"site":"nke","facets":{"gb":{"locations":["53aa8f3ea4191001f60f29eaf76e0000","975e722550c21001bb8cb1eac0ec0000","53aa8f3ea4191001f60ee5ba6d420000","53aa8f3ea4191001f61237ee8bbb0000","24623101e3f11000a8f463330ab50000","975e722550c21001df1d3178cda00000","53aa8f3ea4191001f6118d68ebeb0000","53aa8f3ea4191001f612eb0f79c60000","53aa8f3ea4191001f611590563550000","53aa8f3ea4191001f60f95cecd470000","53aa8f3ea4191001fb508d6ed0290000","975e722550c21001bc19d727bfea0000","53aa8f3ea4191001fb47f432898b0000","53aa8f3ea4191001f60eeb2a6fc60000","8f157e212b271001ded90e3119300000","53aa8f3ea4191001f611569d39650000","e8dea2aff3931001bc51f496cc1b0000","5b190231131c1001bd8590016a560000"]}}}'::jsonb),
  -- locations: United Kingdom (9)
  ('workday', 'roche', 'Roche', 'roche', ARRAY['gb'], true, 1, 'roche.com', '{"tenant":"roche","wd":3,"site":"roche-ext","facets":{"gb":{"locations":["54c59631019f019c71c5aa479f7786e0"]}}}'::jsonb),
  -- sampled "Resource Delivery Executive" — 6366 chars of description
  ('jsonld', 'british-airways', 'British Airways', 'british airways', ARRAY['gb'], true, 1, 'ba.com', '{"sitemapUrl":"https://careers.ba.com/sitemap.xml","jobUrlPattern":"\\/(job|jobs|vacancy|vacancies|position|positions|opportunity|opportunities)\\/"}'::jsonb)
ON CONFLICT (source, account) DO UPDATE SET
  company      = EXCLUDED.company,
  company_norm = EXCLUDED.company_norm,
  markets      = EXCLUDED.markets,
  max_pages    = EXCLUDED.max_pages,
  domain       = EXCLUDED.domain,
  params       = EXCLUDED.params;
  -- `enabled` deliberately not overwritten: re-running must not switch a board
  -- an admin has turned off back on.
